apiVersion: apps/v1
kind: Deployment
metadata:
  name: canary-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-test
      track: canary
  template:
    metadata:
      labels:
        app: nodejs-test
        track: canary
    spec:
      containers:
      - name: canary-app
        image: renardarv/nodejs-test:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2000
