apiVersion: v1
kind: Service
metadata:
  name: stable-service
  labels:
    app: nodejs-test
spec:
  type: LoadBalancer
  selector:
    app: nodejs-test
  ports:
    - name: http
      port: 8080
      targetPort: 2000
      protocol: TCP
